apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  title: Sample Service
  description: |
    A service for testing Backstage functionality. Configured for GitHub Actions and
    Sentry.
  labels:
    tier: "3"
  links:
    - url: https://www.notion.so/roadie/Sample-Service-e067465e56a14ae9b0507f8559f6aa26
      title: Datadog
      icon: dashboard
  tags:
    - test
    - js
    - demo
  annotations:
    github.com/project-slug: zekai-rai/roadie-sample-service
    backstage.io/techdocs-ref: url:https://github.com/zekai-rai/roadie-sample-service/tree/master
    qameta.io/allure-project: asdf
spec:
  type: service
  owner: sample-team
  lifecycle: production
  system: sample-system
  providesApis:
    - sample-service
  dependsOn:
    - Component:sample-service-2
    - Resource:sample-s3-bucket

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: Sentry JS
  name: sentry-js
  description: A JS client which communicates with the Sentry HTTP API.
spec:
  type: library
  lifecycle: production
  owner: sample-team
  system: sample-system
  subcomponentOf: sample-service
